permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
advanced:
  network_key:
    - 135
    - 188
    - 53
    - 126
    - 223
    - 71
    - 51
    - 169
    - 69
    - 231
    - 3
    - 228
    - 82
    - 114
    - 42
    - 14
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xf84477fffe9ce83b':
    friendly_name: '0xf84477fffe9ce83b'
